name: idf
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pip
  - setuptools
  - scikit-image
  - scikit-learn
  - scipy
  - tensorboard
  - tensorboard-data-server
  - trimesh
  - imageio
  - matplotlib
  - pyopengl
  - pykdtree
  - tqdm
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch==2.10.0
    - torchvision
    - pillow
    - pysdf
    - pymeshlab
    - pyrender
